### ISSUE TITLE
No syntax highlighting inside curly brackets in the template

### ISSUE THREAD

**Issue by mikkelsvartveit** [leafOfTree/vim-svelte-plugin#20]
Hi! I'm not getting any syntax highlighting when writing Javascript inside curly brackets in the template. Not sure if this is a bug or if it's just not implemented, but I thought I'd let you know! 

<img width="445" alt="image" src="https://user-images.githubusercontent.com/30391413/196004268-e9bf5bef-1aff-476a-92f1-7247289e0e5c.png">

**Comment by leafOfTree** [comment]
Hi, thanks! It was a bug.
It should be fixed by https://github.com/leafOfTree/vim-svelte-plugin/commit/e42a7514e447802c7a01551b161ffdad0f996b01. Please check it out and let me know if any issues.
![Screen Shot 2022-10-20 at 15 48 47](https://user-images.githubusercontent.com/13349592/196888554-82a14bac-179b-40be-8386-ae5e3b6188ee.png)

**Comment by leafOfTree** [comment]
I'm closing the issue. Feel free to reopen it if needed.
